version: "3"
services:
  backend:
    build: .
    ports:
      - 3333:3333
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
        - 27017:27017
    environment:
      - AUTH=no

